general.import = [
  "/Users/cullback/Documents/atlas/repos/dotfiles/alacritty/catppuccin-frappe.toml"
]

[window]
option_as_alt = "OnlyLeft"
# decorations = "Buttonless"  # remove title bar

# [keyboard]
# bindings = [
#   { key = "Left",  mods = "Command", chars = "\u001bOH" },
#   { key = "Right", mods = "Command", chars = "\u001bOF" },
# ]
