general.import = [
  "./catppuccin-frappe.toml"
]

[window]
option_as_alt = "OnlyLeft"
# decorations = "Buttonless"  # remove title bar

[keyboard]
# rebind cmd left+right as home and end
bindings = [
  { key = "Left",  mods = "Command", chars = "\u001bOH" },
  { key = "Right", mods = "Command", chars = "\u001bOF" },
]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
