[user]
email = "cullback@fastmail.com"
name = "cullback"
username = "cullback"

[init]
defaultBranch = "main"

# [delta]
# side-by-side = true

[core]
editor = "hx"
pager = "delta"
excludesfile = "~/.gitignore_global"
hooksPath = "/home/user/gitconfig/hooks"

[column]
ui = "auto"

[branch]
sort = "-committerdate"

[tag]
sort = "version:refname"

[diff]
algorithm = "histogram"
colorMoved = "plain"
mnemonicPrefix = true
renames = true

[push]
default = "simple"
autoSetupRemote = true
followTags = true

[fetch]
prune = true
pruneTags = true
all = true


# https://blog.gitbutler.com/how-git-core-devs-configure-git/
