# https://github.com/helix-editor/helix/blob/master/languages.toml

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["pyright"]
auto-format = true

[[language]]
name = "markdown"
auto-format = true

[language.formatter]
command = "dprint"
args = ["fmt", "--config", "~/.config/dprint/dprint.json", "--stdin", "md"]

[[language]]
name = "nix"
formatter = { command = "nixfmt" }
auto-format = true
