[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = [ "pyright" ]
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "mdformat", args = ["--number", "-"] }
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixfmt" }
auto-format = true
