keys:
  - &devy age19j6h7sszvw2huedumsen5vpkz5250rrw8epjje4snhdyxdl4narsxtl9u4
  - &atlantix age1m2k0n7d2ggfj429rrs7zqgxw8tfy29ewvt48n37k5x5xjdln5dls3yc2wf

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *devy
          - *atlantix
