# main tools
brew "fish"
brew "fzf"
brew "git"
brew "gitui"
brew "helix"
brew "just"
brew "yazi"
brew "zellij"
brew "starship"

brew "bat"
brew "dust"
brew "eza"
brew "fd"
brew "ripgrep"
brew "sd"

# neat tools
brew "qsv"
brew "b2-tools"
brew "mas"
brew "pipx"
brew "git-delta"
brew "yt-dlp"

# languages
brew "python"
brew "ruff"      # python linter and formatter
brew "pyright"   # python type checker
brew "rustup"    # rust tooling
brew "marksman"  # markdown formatter
brew "typst"

# mac apps
cask "karabiner-elements"
cask "alacritty"
cask "qbittorrent"
cask "iina"
cask "syncthing-app"
cask "modern-csv"
cask "qlmarkdown"
cask "ogdesign-eagle"
cask "google-chrome"
cask "jellyfin"
cask "zed"
cask "1password"
cask "netnewswire"
cask "claude"
cask "calibre"
cask "keepassxc"
cask "utm"
cask "mountain-duck"

# fonts
cask "font-fira-code-nerd-font"

# mac app store apps
mas "Wipr 2", id: 1662217862
mas "WhatsApp Messenger", id: 310633997
mas "Cake Wallet", id: 1334702542
